### ISSUE TITLE
US 01.01.01 - Have Items

### ISSUE THREAD

**Issue by nortif8** [CMPUT301F23T21/EZVault#1]
# Original Description
 As an owner, I want to add an item to my items, with a date of purchase or acquisition, brief description, make, model, serial number (if applicable), estimated value, and comment.

# Description
Owners should be able to add items with the following:
1. date of purchase/acquisition
2. description of item
3. make
4. model
5. serial number (optional)
6. estimated value
7. comment

# Acceptance Criteria
- [x] owner should have list of items
- [x] owner should be able to add an item to the list
- [x] items should have a(n)
    - date of purchase/acquisition
    - description
    - make
    - model
    - serial number (optional)
    - estimated value
    - comment

# Unknowns
n/a

**Comment by nortif8** [comment]
Third task fulfilled by #37.

**Comment by maodus** [comment]
First task fulfilled by #60

**Comment by maodus** [comment]
Closed by #66
